//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPE3_genieco_v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class montantRegion
    {
        public int idRegion { get; set; }
        public string idFraisForfait { get; set; }
        public double montant { get; set; }
    
        public virtual FraisForfait FraisForfait { get; set; }
        public virtual Region Region { get; set; }
    }
}
